#!/bin/bash
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=1:mem=32gb

module load anaconda3/personal

cd $PBS_O_WORKDIR

source activate
conda activate envFYP

# Specify the list of cant and sweep angles
CANT_LIST="-120 -105 -90 -75 -60 -45 -30 -15 0 15 30 45 60 75 90 105 120"
SWEEP_LIST="-20 -10 0 10 20"

python3 main_runAutomation.py -np 8 -mem 32 -time 8 -geo 1 -mesh 1 -prism-layer 0 -cfd 1 -cfd-solver euler -aso 1 -aso-solver euler -cant-list $CANT_LIST -sweep-list $SWEEP_LIST